name: Fly Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'         # Ignores alterações em arquivos Markdown (ex: README.md)
      - '.gitignore'    # Ignores alterações no .gitignore
      - '.env.example'  # Ignores exemplos de variáveis

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}